definitions:
  domain.Person:
    properties:
      age:
        type: integer
      hobbies:
        items:
          type: string
        type: array
      id:
        type: string
      name:
        type: string
    type: object
  dto.CreatePerson:
    properties:
      age:
        maximum: 120
        minimum: 0
        type: integer
      hobbies:
        items:
          type: string
        type: array
      name:
        type: string
    required:
    - age
    - hobbies
    - name
    type: object
info:
  contact: {}
paths:
  /api/v1/persons:
    get:
      consumes:
      - application/json
      description: Retrieve a list of persons
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Person'
            type: array
      summary: Get all persons
      tags:
      - Persons
    post:
      consumes:
      - application/json
      description: Add a new person to the database
      parameters:
      - description: Person data
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePerson'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Person'
        "400":
          description: Invalid input
          schema:
            type: string
      summary: Add a new person
      tags:
      - Persons
  /api/v1/persons/{personId}:
    delete:
      consumes:
      - application/json
      description: Delete a person by their ID
      parameters:
      - description: ID of the person
        in: path
        name: personId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Person not found
          schema:
            type: string
      summary: Delete a person
      tags:
      - Persons
    get:
      consumes:
      - application/json
      description: Retrieve a person by their ID
      parameters:
      - description: ID of the person
        in: path
        name: personId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Person'
        "404":
          description: Person not found
          schema:
            type: string
      summary: Get person by ID
      tags:
      - Persons
    put:
      consumes:
      - application/json
      description: Update a person by their ID
      parameters:
      - description: ID of the person
        in: path
        name: personId
        required: true
        type: string
      - description: Updated person data
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePerson'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Person'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Person not found
          schema:
            type: string
      summary: Update an existing person
      tags:
      - Persons
swagger: "2.0"
